#%RAML 1.0 DataType

type: object
properties: 
  Location: string
  Time: string
  WindSpeed: string
  Visibility: string
  SkyConditions: string
  Temperature: integer
  DewPoint: string
  RelativeHumidity: integer
  Status: string